development:
  adapter: postgresql
  encoding: unicode
  database: knowledgebase_development
  pool: 5
  username: cody
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: knowledgebase_test
  pool: 5
  username: cody
  password:
